packages:
  - .
  - .playground

allowBuilds:
  better-sqlite3: false
  esbuild: false
  unrs-resolver: false
  vue-demi: false

ignoredBuiltDependencies:
  - vue-demi

minimumReleaseAgeExclude:
  - '@nuxt/ui@4.11.0'
  - cloudflare-ai-search-sync@0.0.1
